# Generated file...
---
- name: bookbinder-release-complete
  type: s3
  source:
    bucket: concourse-interim-steps
    versioned_file: bookbinder-release-complete.tar.gz
    private: true
    access_key_id: "{{aws-access-key}}"
    secret_access_key: "{{aws-secret-key}}"
- name: concourse-scripts-docs-master
  type: git
  source:
    uri: git@github.com:pivotal-cf/concourse-scripts-docs.git
    branch: master
    private_key: "{{github-deploy-bot}}"
- name: docs-book-pks-1.2
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-book-pks.git
    branch: '1.2'
    private_key: "{{github-deploy-bot}}"
- name: docs-layout-repo-master
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-layout-repo.git
    branch: master
    private_key: "{{github-deploy-bot}}"
- name: docs-pks-1.2
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-pks.git
    branch: '1.2'
    private_key: "{{github-deploy-bot}}"
