---
index:
  analysis:
    filter:
      synonym:
        type: synonym
        ignore_case: true
        expand: true
        synonyms:
        - PCF, Pivotal Cloud Foundry, Pivotal CF
    analyzer:
      default:
        tokenizer: standard
        filter:
        - synonym
        - stop
mappings:
  page:
    properties:
      title:
        type: string
      text:
        type: string
        analyzer: default
      headings:
        type: string
        analyzer: default
      url:
        type: string
        index: not_analyzed
      product_name:
        type: string
        index: not_analyzed
      product_version:
        type: string
        index: not_analyzed
      summary:
        type: string
        index: not_analyzed

