---
- book: pivotal-cf/docs-book-pks
  book_branch: '1.3'
  routes: []
  app_name: docs-pks-1-3
  deployments:
  - name: staging
    depends_on: bind
    trigger: true
    endpoint: https://api.run.pivotal.io
    organization: cf-docs-sandbox
    space: development
    routes:
      - domain: cfapps.io
        hostname: docs-pks-staging
        path: runtimes/pks/1-3
  - name: production
    depends_on: staging
    trigger: false
    endpoint: https://api.run.pivotal.io
    organization: cf-docs-sandbox
    space: development
    routes:
      - domain: cfapps.io
        hostname: docs-pks-prod
        path: /runtimes/pks/1-3
